GET http://localhost:3001/api/v1/products
###
POST http://localhost:3001/api/v1/products
Content-Type: application/json

{
    "name": "shoes",
    "picture": "https://picsum.photos/200",
    "stockBalance": 20000,
    "price": 10000,
    "warehouseId": 9,
    "description": "nike"
}
###
GET http://localhost:3001/api/v1/products/5fa5ea0cb6433e36b0b8aeba

###
PATCH http://localhost:3001/api/v1/products/5fa5ea0cb6433e36b0b8aeba
Content-Type: application/json

{
  "name": "hey"
, "picture": "https://picsum.photos/200"
, "stockBalance": 200
, "price": 1000
, "warehouseId": 3
, "description": "sample description"
}

###
DELETE http://localhost:3001/api/v1/products/5fa5ea0cb6433e36b0b8aeba

###
PATCH  http://localhost:3001/api/v1/products/5fa5ea0cb6433e36b0b8aeba/restore

###
GET  http://localhost:3001/api/v1/products/trash



###
GET  http://localhost:3001/api/foreign/warehouses

###
GET  http://localhost:3001/api/foreign/warehouses/1
