get http://localhost:3001/



###
### foreign api emulation
###
### /foreign
GET http://localhost:3001/api/foreign

### /foreign/warehouses
GET http://localhost:3001/api/foreign/warehouses

### /foreign/warehouses/:id
GET http://localhost:3001/api/foreign/warehouses/10

###
### api
###
GET http://localhost:3001/api/v1


###
GET http://localhost:3001/api/v1/products/feedme?pass=alohomora


###
GET http://localhost:3001/api/v1/products
# ?page=2
# &per_page=10

###
GET http://localhost:3001/api/v1/products/search?
# ?page=2
# &per_page=10

###
POST http://localhost:3001/api/v1/products
Content-Type: application/json

{
    "name": "shoes",
    "picture": "https://picsum.photos/200",
    "stockBalance": 20000,
    "price": 10000,
    "warehouseId": 9,
    "description": "nike"
}

###
GET http://localhost:3001/api/v1/products/5fa0f839ebf54c2c2dea67b6

###
POST http://localhost:3001/api/v1/products/5fa093233e52ecd30fb6ffbc
Content-Type: application/json

{
  "name": "hey"
# , "picture": "https://picsum.photos/200"
# , "stockBalance": 200
# , "price": 1000
, "warehouseId": 3
# , "description": "sample description"
}

###
DELETE http://localhost:3001/api/v1/products/5fa291e891e8d18267f48b14
