###
### foreign api emulation
###
### /foreign
GET http://localhost:3001/api/foreign

### /foreign/warehouses
GET http://localhost:3001/api/foreign/warehouses

### /foreign/warehouses/:id
GET http://localhost:3001/api/foreign/warehouses/1

###
### api
###
GET http://localhost:3001/api/v1


###
GET http://localhost:3001/api/v1/products/feedme?pass=alohomora


###
GET http://localhost:3001/api/v1/products
?page=2
&limit=10
# &warehouseId=2,3
# &price[min]=100
# &price[max]=300

###
POST http://localhost:3001/api/v1/products
content-type: application/json

{
    "name": "shoes",
    "picture": "https://picsum.photos/200",
    "stockBalance": 20000,
    "price": 10000,
    "warehouseId": 9,
    "description": "nike"
}

###
GET http://localhost:3001/api/v1/products/5f9e4684bc99185da9944059

###
POST http://localhost:3001/api/v1/products/5f9e4684bc99185da9944059
content-type: application/json

{
    "name": "",
    # "picture": "https://picsum.photos/200",
    # "stockBalance": 200330,
    # "price": 1000,
    # "warehouseId": 3,
    # "description": "sample description"
}

###
DELETE http://localhost:3001/api/v1/products/5f9ba86e211ecd5710a38f5f
